---
- name: Red Hat account id
  set_fact:
    sat_account_id: "{{ organization.redhat_account_number }}"
  tags: query_satellite
- name: If an account number is findable
  block:
  - debug:
      msg: "Account {{ sat_account_id }} associated with organization {{ organization.id }}"
  - name: "Make configuration directory for account {{ sat_account_id }}"
    file:
      path: "{{ receptor_config_dir }}/rh_{{ sat_account_id }}"
      state: directory
      mode: 0755
  - name: "Make a data directory for account {{ sat_account_id }}"
    file:
      path: "{{ receptor_data_dir }}/rh_{{ sat_account_id }}"
      state: directory
      mode: 0755
  - name: "Write x.509 certificate for account {{ sat_account_id }}"
    copy:
      dest: "{{ receptor_config_dir }}/rh_{{ sat_account_id }}/cert.pem"
      mode: 0644
      content: "{{ organization.cert }}"
  - name: "Write x.509 key for account {{ sat_account_id }}"
    copy:
      dest: "{{ receptor_config_dir }}/rh_{{ sat_account_id }}/key.pem"
      mode: 0400
      content: "{{ organization.key }}"
  - name: Generate a UUID for this Receptor node
    shell: "uuidgen > {{ receptor_config_dir }}/rh_{{ sat_account_id }}/uuid"
    args:
      creates: "{{ receptor_config_dir }}/rh_{{ sat_account_id }}/uuid"
  - name: "Write Receptor configuration for account {{ sat_account_id }}"
    template:
      dest: "{{ receptor_config_dir }}/rh_{{ sat_account_id }}/receptor.conf"
      mode: 0400
      owner: foreman-proxy
      src: receptor.conf.j2
  when: sat_account_id != ""
  tags: query_satellite
