---
- name: Extract node ID from configuration
  set_fact:
    receptor_node_id: "{{ lookup('ini', 'node_id section=receptor file='+receptor_config_dir+'/'+account_dir+'/receptor.conf') }}"
- name: Create Source in c.rh.c
  uri:
    url: "https://{{ c_rh_c_host }}/api/sources/v1.0/sources"
    client_cert: "{{ receptor_config_dir }}/{{ account_dir }}/cert.pem"
    client_key: "{{ receptor_config_dir }}/{{ account_dir }}/key.pem"
    method: "POST"
    body:
      name: "Satellite {{ satellite_uuid }}"
      source_type_id: "{{ source_type_id }}"
      source_ref: "{{ satellite_uuid }}"
    body_format: json
    return_content: yes
  register: source_create_response
- name: Add endpoint to Source
  uri:
    url: "https://{{ c_rh_c_host }}/api/v1.0/endpoints"
    client_cert: "{{ receptor_config_dir }}/rh_{{ account_dir }}/cert.pem"
    client_key: "{{ receptor_config_dir }}/rh_{{ account_dir }}/key.pem"
    method: "POST"
    body:
      source_id: "{{ source_create_response.json.id }}"
      receptor_node: "{{ receptor_node_id }}"
